language: python
python:
  - "2.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
# command to install dependencies
install:
  - pip install numpy Bio --use-mirrors 
# command to run tests
script: nosetests 
