language: python
python:
  - "2.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
# command to install dependencies
before_install:
  - sudo apt-get install -qq libatlas3gf-base libatlas-dev
install:
  - pip install -q -U numpy --use-mirrors
  - pip install scipy
  - pip install -q biopython --use-mirrors 
# command to run tests
script: nosetests

branches:
  only:
    - master
